name: ci

on:
    push:
        branches: [master]

jobs:
    test:
        runs-on : ubuntu-latest
        steps:
            - name: upload code climate
              uses: paambaati/codeclimate-action@v3.0.0